---
title: "1-Wasserstein Metric and Generalizations"
author: Seyit Emre Duzoylum.
---

Let $\mathcal{M}$ denote the space of all Radon measures on $\mathbb{R}^d$ with finite mass. Moreover, let $\mathcal{M}^p$ denote the space of Radon measures with finite $p^{th}$ moment, that is, $\int_{\mathbb{R}^d} |x|^p d\mu(x) < \infty$. Then, for $\mu,\nu \in \mathcal{M}^p$ with $|\mu|=|\nu|$ the $p$-Wasserstein distance is defined as<ref name="Picolli" /> :$W_p(\mu,\nu) = ( |\mu| \underset{ \pi \in \Gamma(\mu,\nu) }{ \inf } \int_{\mathbb{R}^d \times \mathbb{R}^d } |x-y|^p d\pi(x,y))^{1/p}$ where $\Gamma(\mu,\nu)$ denotes the set of all transport plans from $\mu$ to $\nu$. Note that, if we restrict $\mu$ and $\nu$ to be probability measures, then the $p$-Wasserstein distance can be seen as a special case of the [Kantorovich Problem](http://34.106.105.83/wiki/Kantorovich_Problem), where $c(x_1,x_2) = |x_1-x_2|^p$. Furthermore, if we let $\mathcal{P}^p$ denote the space of probability measures on $\mathbb{R}^d$ with finite $p^{th}$ moment, then $W_p$ defines a metric on $\mathcal{P}^p$.

# Measures with unequal mass and signed measures

The classical Wasserstein distance can be generalized for measures with unequal mass by allowing the addition and removal of mass to $\mu$ and $\nu$.<ref name="Picolli" /> In this case, there is unit cost $a >0$ for the addition or removal of mass from both $\mu$ and $\nu$, whereas the transport cost of mass between $\mu$ and $\nu$ stays the same with the classical [Kantorovich Problem](http://34.106.105.83/wiki/Kantorovich_Problem); multiplied with some rate $b >0$ .

**Definition.**<ref name="Picolli" /> For some $a,b \in \mathbb{R}_{++}$ and $p \geq 1$, **the generalized Wasserstein distance** ${W}_p^{a,b}$ is given by :${W}_p^{a,b}(\mu,\nu) = \underset{\underset{ |\bar{\mu}| = |\bar{\nu}|  }{\bar{\mu},\bar{\nu} \in \mathcal{M}^p}}{\inf} (a(|\mu-\bar{\mu}|) + a(|\nu-\bar{\nu}|) + b {W}_p(\bar{\mu},\bar{\nu}) )$ where ${W}_p(\bar{\mu},\bar{\nu})$ is the classical $p$-Wasserstein distance for measures with equal mass.

Note that, under this definition ${W}_p^{a,b}$ defines a metric on $\mathcal{M}$, and $(\mathcal{M},{W}_p^{a,b})$ is a complete metric space.<ref name="Picolli" />. Furthermore, this generalization allows one to extend the $1$-Wasserstein distance to the signed Radon measures as well. Let us denote the space of all signed Radon measures on $\mathbb{R}^d$ with finite mass with $\mathcal{M}^s(\mathbb{R}^d)$.

**Definition.**<ref name="Picolli2" /> For some $a,b \in \mathbb{R}_{++}$, **the generalized Wasserstein distance for signed measures** $\mathbb{W}_1^{a,b}$ is given by :$\mathbb{W}_1^{a,b}(\mu,\nu) = W_1^{a,b}(\mu_+ + \nu_- , \mu_- + \nu_+)$ where $\mu_+,\nu_-,\mu_-,\nu_+$ are any measures in $\mathcal{M}(\mathbb{R}^d)$ such that $\mu = \mu_+ - \mu_-$ and $\nu = \nu_+ - \nu_-$.

Moreover, if we let $||\mu||^{a,b} = \mathbb{W}_1^{a,b}(\mu,0) =  W_1^{a,b}(\mu_+ , \mu_- )$, then $(\mathcal{M}^s,||\mu||^{a,b})$ is a normed vector space. However, as opposed to the completeness of $(\mathcal{M},{W}_p^{a,b})$ , $(\mathcal{M}^s,||\mu||^{a,b})$ fails to be a Banach space.<ref name="Picolli2" />

# Duality

As a special case of the [Kantorovich Dual Problem](http://34.106.105.83/wiki/Kantorovich_Dual_Problem_(for_general_costs)) when $c(x_1,x_2) = |x_1-x_2|$, $1$-Wasserstein metric has the following dual characterization.

**Theorem.**<ref name="Villani" /> Let Lip$(\mathbb{R}^d)$ denote the space of all Lipschitz functions on $\mathbb{R}^d$, and let $||\varphi||_{\text{Lip}} = \underset{x\neq y}{\sup} \frac{\varphi(x)-\varphi(y)}{|x-y|}$. Then,

:   $W_1(\mu,\nu) = \sup \{ \int_{\mathbb{R}^d} \varphi d(\mu-\nu) : \varphi \in \mathcal{C}^0_c, \text{ } ||\varphi||_{\text{Lip}} \leq 1 \}$. In a similar spirit, this duality result can be extended for generalized $1$-Wasserstein distances $W^{1,1}_1$ and $\mathbb{W}^{1,1}_1$ as well, where $a$ and $b$ are taken as 1. For measures with unequal mass, when the additional constraint $||\varphi||_\infty \leq 1$ is imposed on the test functions, it holds that<ref name="Picolli3" />

:$W^{1,1}_1(\mu,\nu) = \sup \{ \int_{\mathbb{R}^d} \varphi d(\mu-\nu) : \varphi \in \mathcal{C}^0_c, \text{ } ||\varphi||_\infty \leq 1, \text{ } ||\varphi||_{\text{Lip}} \leq 1 \}$.

In terms of the generalized 1-Wasserstein metric for signed measures, when we relax the compact support condition on the test functions we obtain the equivalent duality characterization as follows.<ref name="Picolli2" />

:$\mathbb{W}^{1,1}_1(\mu,\nu) = \sup \{ \int_{\mathbb{R}^d} \varphi d(\mu-\nu) : \varphi \in \mathcal{C}^0_b, \text{ } ||\varphi||_\infty \leq 1, \text{ } ||\varphi||_{\text{Lip}} \leq 1 \}$.

# References

<references> <ref name="Picolli"> [Piccoli, B., Rossi, F. Generalized Wasserstein Distance and its Application to Transport Equations with Source. Arch Rational Mech Anal 211, 335–358 (2014). https://doi.org/10.1007/s00205-013-0669-x](https://rdcu.be/cGRJz) </ref>

<ref name="Picolli2"> [Piccoli, B., Rossi, F., Tournus M. A Wasserstein norm for signed measures, with application to nonlocal transport equation with source term. arXiv:1910.05105 (2019).](https://arxiv.org/pdf/1910.05105.pdf) </ref>

<ref name="Picolli3"> [Piccoli, B., Rossi, F. Piccoli, B., Rossi, F. On Properties of the Generalized Wasserstein Distance. Arch Rational Mech Anal 222, 1339–1365 (2016). https://doi.org/10.1007/s00205-016-1026-7](https://rdcu.be/cGR1n) </ref>

<ref name="Villani">[C. Villani, *Topics in Optimal Transportation*, Chapter 1.](https://people.math.gatech.edu/~gangbo/Cedric-Villani.pdf)</ref> </references>
