project:
  type: website
  render:
    - "*.qmd"
  resources:
    - CNAME
    - .nojekyll

website:
  title: "OT WIKI"
  site-url: https://www.otwiki.xyz/
  navbar:
    left:
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    link-external-icon: false

editor: visual

