---
title: "Suggestions of Articles to Revise"
bibliography: bibliography.bibtex
---

Below, you can find a list of suggestions for articles to revise.

If you choose to revise one of these articles, let me know, and I will remove it from the list below.

 
-   [Optimal Transport in One Dimension](https://www.otwiki.xyz/wiki/Optimal_Transport_in_One_Dimension) - Yusen will revise - This article could benefit from a major reorganization, adding/removing some sections (such as the linear cost example), and stating the main theorem in a higher level of generality, as in Santambrogio Theorem 2.9 p63 of Optimal Transport for Applied Mathematicians
- [Kantorovich Dual Problem for General Costs](https://www.otwiki.xyz/wiki/Kantorovich_Dual_Problem_(for_general_costs)) - This article could benefit from editing throughout. It would be good to expand the final section on c-convcave functions, stating and explaining Santambrogio Proposition 1.11 p12 of Optimal Transport for Applied Mathematicians
- [Kantorovich Dual Problem (for c(x,y) = d(x,y)^2 where d is a metric)](https://www.otwiki.xyz/wiki/Kantorovich_Dual_Problem_(for_c(x,y)_%3D_d(x,y)%5E2_where_d_is_a_metric)) - This article could benefit from editing throughout, especially regarding the latex formatting. The condition that mu does not give mass to small sets needs to be corrected. This article should more thoroughly reference the other article on the Kantorovich dual probelm. It should prove the relationship between c-concave functions and convex conjugates, as in Santambrogio's Proposition 1.21, p16 of Optimal Transport for Applied Mathematicians. The relationship between (DP) and (DP-var), as Santambrogio refers to them, needs to be explained. (You do not need to use the notation DP and DP-var.)
- [Wasserstein barycenters and applications in image processing](https://www.otwiki.xyz/wiki/Wasserstein_barycenters_and_applications_in_image_processing) - This article could benefit from editing throughout, with more precise statements of the main results. It should also be revised to mention [recent work](https://arxiv.org/abs/2411.06838) on barycenters with positive and negative weights.
- [Discrete Optimal Transport](https://www.otwiki.xyz/wiki/Discrete_Optimal_Transport) - Charles will revise - This article could benefit from editing throughout. Several sections just have a few words as a placeholder and could be  expanded. (The dual problem should be stated explicitly and a reference should be added to the wiki article on the dual problem.) The latex formatting could be simplified and made easier to read. Everything could be explained for general costs, rather than quadratic costs. The results of Exercise 25 could be included.
- [Sinkhorn's Algorithm](https://www.otwiki.xyz/wiki/Sinkhorn%27s_Algorithm) - Jack Pfaffinger will revise - This article could benefit from editing throughout. The wiki article on discrete optimal transport should be referenced. The interpretation of the Sinkhorn algorithm in terms of the corresponding dual probalm and in terms of convex projections should be explained. (See Peyre and Cuturi)
- [Sliced Wasserstein Distance](https://www.otwiki.xyz/wiki/Sliced_Wasserstein_Distance) - This article could benefit from editing throughout. Recent contributions by [Kitagawa and Takatsu](https://arxiv.org/abs/2311.15874) and [Park and Slepcev](https://arxiv.org/abs/2311.05134) should be summarized.
- [Gradient flows on Hilbert Spaces](https://www.otwiki.xyz/wiki/Gradient_flows_in_Hilbert_spaces) - The organization of this article could be greatly improved. Currently, there is an over emphacsis on the Moreau Yosida regularization. Also, the other wiki article on the MY regularization should be cited. The latex formatting could be improved throughout. The statements in the Examples and Applications section could be made more rigorous and more organized.