---
title: "Continuous-Time MOT and Skorokhod Embedding"
author: Qijin Shi
bibliography: bibliography.bib
---

This article is an extension of the previous Wiki article [Martingale optimal transport and mathematical finance](https://www.otwiki.xyz/wiki/Martingale_optimal_transport_and_mathematical_finance). We set up a robust and dynamic connection to bridge martingale optimal transport (MOT) with continuous-time mathematical finance, providing a model-independent framework for robust hedging without assuming a specific stochastic model for the asset dynamics. The main technical difficulty in the continuous-time setting is the construction of a martingale coupling measure on the space of sample paths, e.g., $C([0, T], \mathbb{R})$; or equivalently, the construction of a continuous martingale price process matching all the given marginals. The [Skorokhod embedding problem (SEP)](https://en.wikipedia.org/wiki/Skorokhod%27s_embedding_theorem) plays the role of converting this technical difficulty into the problem of finding a stopping time for a Brownian motion that reproduces the target marginals. By illustrating several explicit SEP solutions, we give applications to robust hedging and pricing in the settings of continuous-time MOT.

This article requires basic knowledge of stochastic analysis, mainly [stochastic calculus](https://en.wikipedia.org/wiki/Stochastic_calculus) and [Itô's formula](https://en.wikipedia.org/wiki/It%C3%B4%27s_lemma). The main reference is @henrylabordere2017model, Chapter 4.

## Continuous-time MOT

The setting of continuous-time MOT is similar to the discrete case in the previous Wiki article [Martingale optimal transport and mathematical finance](https://www.otwiki.xyz/wiki/Martingale_optimal_transport_and_mathematical_finance), except the underlying price process is continuous. We describe it via a probability measure on a path space, e.g., $C([0, T], \mathbb{R}_+)$. Throughout this article, we assume a zero interest rate.

### Probabilistic setup

Let $\Omega \equiv\left\{\omega \in C\left([0, T], \mathbb{R}_{+}\right): \omega_0=0\right\}$ be the canonical space equipped with the uniform norm $\|\omega\|_{\infty} \equiv \sup _{0 \leq t \leq T}|\omega(t)|, B$ the canonical process, i.e., $B_t(\omega) \equiv \omega(t)$ and $\mathcal{F} \equiv\left\{\mathcal{F}_t\right\}_{0 \leq t \leq T}$ the filtration generated by $B: \mathcal{F}_t=$ $\sigma\left\{B_s, s \leq t\right\}. \mathbb{P}^0$ is the Wiener measure. $S_0$ is some given initial value in $\mathbb{R}_{+}$, and we denote

$$
S_t \equiv S_0+B_t \text { for } t \in[0, T]
$$

For any $\mathcal{F}$-adapted process $\sigma$ and satisfying $\int_0^T \sigma_s^2 d s<\infty, \mathbb{P}^0$-a.s., we define the probability measure on $(\Omega, \mathcal{F})$ :

$$
\mathbb{P}^\sigma \equiv \mathbb{P}^0 \circ\left(S^\sigma\right)^{-1} \text { where } S_t^\sigma \equiv S_0+\int_0^t \sigma_r d B_r, t \in[0, T], \mathbb{P}^0-\text { a.s. }
$$

Then $S$ is a $\mathbb{P}^\sigma$-local martingale. We denote by $\mathcal{M}^c$ the collection of all such probability martingale measures on $(\Omega, \mathcal{F})$, i.e.

$$
\mathbb{E}_{\mathbb{P}^\sigma}\left[S_s \mid \mathcal{F}_t\right]=S_t \quad \forall 0\leq t\leq s\leq T.
$$

In other words, the set of all $S^{\sigma}$ is the set of all martingale price processes we consider and $\mathcal{M}^c$ is the set of all martingale probability measures induced on the canonical space by these price processes.

The [quadratic variation process](https://en.wikipedia.org/wiki/Quadratic_variation) $\langle S\rangle=\langle B\rangle$ takes values in the set of all nondecreasing continuous functions. Note that the quadratic variation can be defined pathwise as the limsup of the corresponding discrete counterpart with conveniently chosen mesh of the time partition. The dependence of the quadratic variation on the underlying probability measure $\mathbb{P} \in \mathcal{M}^{\text {c }}$ can therefore be dropped. Finally, $\mathcal{M}^c(\mu) \equiv\left\{\mathbb{P}^\sigma \in \mathcal{M}^c: S_T^\sigma \stackrel{\mathbb{P}^\sigma}{\sim} \mu\right\}$ where $\mu$ is supported on $\mathbb{R}_{+}$. For the ease of notation, we will delete the superscript $\sigma$ on $S^\sigma$ below.

Additionally, for all $\mathbb{P} \in \mathcal{M}^c$, we denote the set of trading portfolios:

$$
\mathbb{H}_{\mathrm{loc}}^2(\mathbb{P}) \equiv\left\{H \in \mathbb{H}^0(\mathbb{P}): \int_0^T H_t^2 d\langle S\rangle_t<\infty, \mathbb{P}-\text { a.s. }\right\}
$$ Under the self-financing condition, for any admissible portfolio $H$, the portfolio value process

$$
Y_t^H \equiv Y_0+\int_0^t H_s d S_s, t \in[0, T]
$$ is well-defined $\mathbb{P}$-a.s. for every $\mathbb{P} \in \mathcal{M}^c$, whenever $H \in \mathbb{H}_{\text {loc }}^2$. In order to avoid doubling strategies, we introduce the set of admissible portfolios:

$$
\mathcal{H} \equiv\left\{H: H \in \mathbb{H}_{\text {loc }}^2 \text { and } Y^H \text { is a } \mathbb{P}-\text { supermartingale for all } \mathbb{P} \in \mathcal{M}^c\right\}
$$

### Duality formulation

Let $\xi$ be the payoff of an option, defined as an $\mathcal{F}_T$-measurable random variable. This means that the payoff might not depend only on the final price $S_T$, but also on the whole price path. In addition to the continuous-time trading, we assume that the investor can take static positions in Vanilla options with maturities $\left(t_i\right)_{i=1, \ldots, n}$. From the theory of \href{https://en.wikipedia.org/wiki/Risk-neutral_measure}{risk-neutral pricing}, $t_i$-Vanilla defined by the payoff $\lambda_i\left(S_{t_i}\right) \in \mathrm{L}^1\left(\mathbb{P}^i\right)$ has an unambiguous market price given by $\mathbb{E}^{\mathbb{P}^i}\left[\lambda_i\left(S_{t_i}\right)\right]$, see also \href{https://www.otwiki.xyz/wiki/Martingale_optimal_transport_and_mathematical_finance}{this Wiki article} . The robust super-replication price is then defined by:

$$
\begin{array}{r}
\operatorname{MK}_n^{\mathrm{c}}\left(\mathbb{P}^1, \ldots, \mathbb{P}^n\right) \equiv \inf \left\{Y_0: \exists\left(\lambda_i \in \mathrm{~L}^1\left(\mathbb{P}^i\right)\right)_{i=1, \ldots, n} \text { and } H \in \mathcal{H}\right. \\
\left.\bar{Y}_T^{H, \lambda} \geq \xi, \mathbb{P}-\text { a.s. for all } \mathbb{P} \in \mathcal{M}^c\right\}
\end{array}
$$ where $\bar{Y}^{H, \lambda}$ denotes the portfolio value of a self-financing strategy with continuous trading $H$ in the underlying, and static trading $\left(\lambda_i\right)_{i=1, \ldots, n}$ in the $t_i$-Vanillas:

$$
\bar{Y}_T^{H, \lambda} \equiv Y_0+\int_0^T H_s d S_s+\sum_{i=1}^n \lambda_i\left(S_{t_i}\right)-\sum_{i=1}^n \mathbb{E}^{\mathbb{P}^i}\left[\lambda_i\left(S_{t_i}\right)\right]
$$

The financial interpretation is the following: The investor buys at time 0 any Vanilla with payoff $\lambda_i\left(S_{t_i}\right)$ for the price $\mathbb{E}^{\mathbb{P}^i}\left[\lambda_i\left(S_{t_i}\right)\right]$, while trading using the portfolio $H$. That $\bar{Y}_T^{H, \lambda} \geq \xi,$ $\mathbb{P}-$ a.s. for all $\mathbb{P} \in \mathcal{M}^c$ essentially means that under all possible price process, the final wealth of our self-financing strategy is larger than the pay-off of the option $\xi$ with probability one. Thus, $\mathrm{MK}_n^c\left(\mathbb{P}^1, \ldots, \mathbb{P}^n\right)$ is an upper bound on the price of $\xi$ necessary for absence of strong (model-independent) arbitrage opportunities: selling $\xi$ at a higher price, the hedger could set up a portfolio with a negative initial cost and a non-negative payoff under any market scenario.

Similarly, in the case of continuous-time static hedging in Vanillas, we define

$$
\begin{array}{r}
\mathrm{MK}_{\infty}^{\mathrm{c}}\left(\left(\mathbb{P}^t\right)_{t \in(0, T]}\right) \equiv \inf \left\{Y_0: \exists\left(\lambda(t, \cdot) \in \mathrm{L}^1\left(\mathbb{P}^t\right)\right)_{t \in(0, T]} \text { and } H \in \mathcal{H}\right. \\
\left.\bar{Y}_T^{H, \lambda} \geq \xi, \mathbb{P}-\text { a.s. for all } \mathbb{P} \in \mathcal{M}^c\right\},
\end{array}
$$ where $t \mapsto \mathbb{E}^{\mathbb{P}^t}\left[\lambda\left(t, S_t\right)\right] \in \mathrm{L}^1([0, T])$ and $$
\bar{Y}_T^{H, \lambda} \equiv Y_0+\int_0^T H_s d S_s+\int_0^T \lambda\left(t, S_t\right) d t-\int_0^T \mathbb{E}^{\mathrm{P}^t}\left[\lambda\left(t, S_t\right)\right] d t
$$

Now we give the key result from the perspective of OT, the dual formulation of the above robust superhedging price:

**Proposition 4.1 [@henrylabordere2017model]**

Assume $\sup_{\mathbb{P} \in \mathcal{M}^c} \mathbb{E}^\mathbb{P}[\xi^+] < \infty$. Then:

(i) $$
    \operatorname{MK}_n^c(\mathbb{P}^1, \ldots, \mathbb{P}^n) = \inf_{(\lambda_i)} \sum_{i=1}^n \mathbb{E}^{\mathbb{P}^i}[\lambda_i(S_{t_i})] + \sup_{\mathbb{P} \in \mathcal{M}^c} \mathbb{E}^\mathbb{P}\left[\xi - \sum_{i=1}^n \lambda_i(S_{t_i})\right].
    $$

(ii) $$
     \operatorname{MK}_\infty^c((\mathbb{P}^t)) = \inf_{\lambda(t,\cdot)} \int_0^T \mathbb{E}^{\mathbb{P}^t}[\lambda(t, S_t)] dt + \sup_{\mathbb{P} \in \mathcal{M}^c} \mathbb{E}^\mathbb{P}\left[\xi - \int_0^T \lambda(t, S_t) dt\right].
     $$

**Proof**: See [@galichon2014stochastic; @guo2016optimal].

### An intuitive duality formulation assuming a minimax argument

The above dual formulation might seem less intuitive at first glance. Now we give a more intuitive dual formulation assuming a minimax argument holds.

Taking for granted that we can permute the supremum over $\mathbb{P} \in \mathcal{M}^c$ and the infimum over $\left(\lambda_i \in \mathrm{~L}^1\left(\mathbb{P}^i\right)\right)_{i=1, \ldots, n}$, we get $$
 \operatorname{MK}_n^{\mathrm{c}}\left(\mathbb{P}^1, \ldots, \mathbb{P}^n\right)=\sup _{\mathbb{P} \in \mathcal{M}^c\left(\lambda_i \in \mathrm{~L}^1\left(\mathbb{P}^i\right)\right)_{i=1, \ldots, n}} \sum_{i=1}^n \mathbb{E}^{\mathbb{P}^i}\left[\lambda_i\left(S_{t_i}\right)\right] +\mathbb{E}^{\mathbb{P}}\left[\xi-\sum_{i=1}^n \lambda_i\left(S_{t_i}\right)\right]
$$ Then, taking the infimum over $\left(\lambda_i \in \mathrm{~L}^1\left(\mathbb{P}^i\right)\right)_{i=1, \ldots, n}$, we deduce \begin{equation}\label{4.8}
    \operatorname{MK}_n^{\mathrm{c}}\left(\mathbb{P}^1, \ldots, \mathbb{P}^n\right)=\sup _{\mathbb{P} \in \mathcal{M}^c\left(\mathbb{P}^1, \ldots, \mathbb{P}^n\right)} \mathbb{E}^{\mathbb{P}}[\xi]
\end{equation} where $$
\mathcal{M}^c\left(\mathbb{P}^1, \ldots, \mathbb{P}^n\right) \equiv\left\{\mathbb{P} \in \mathcal{M}^c: S_{t_i} \stackrel{\mathbb{P}}{\sim} \mathbb{P}^i, \quad \forall i=1, \ldots, n\right\}
$$ Similarly, taking for granted that we can permute the supremum over $\mathbb{P} \in \mathcal{M}^c$ and the infimum over $\lambda(t, \cdot) \in \mathrm{L}^1\left(\mathbb{P}^t\right), \forall t \in(0, T]$, we get \begin{equation}\label{4.10}
\mathrm{MK}_{\infty}^{\mathrm{c}}\left(\left(\mathbb{P}^t\right)_{t \in(0, T]}\right)=\sup _{\mathbb{P} \in \mathcal{M}^c\left(\left(\mathbb{P}^t\right)_{t \in(0, T]}\right)} \mathbb{E}^{\mathbb{P}}[\xi]
\end{equation} where $$
\mathcal{M}^c\left(\left(\mathbb{P}^t\right)_{t \in(0, T]}\right) \equiv\left\{\mathbb{P} \in \mathcal{M}^c: S_t \stackrel{\mathbb{P}}{\sim} \mathbb{P}^t, \quad \forall t \in(0, T]\right\}
$$

So providing we could justify this minimax argument, our robust superhedging is connected to a MOT: we maximize the cost $\mathbb{E}^{\mathbb{P}}[\xi]$ over the space of martingale measures with marginals $\left(\mathbb{P}^i\right)_{i=1, \ldots, n}\left(\right.$ or $\left.\left(\mathbb{P}^t\right)_{t \in(0, T]}\right)$ and $\mathbb{P}^0=\delta_{S_0}$. If the dual is attained, $\mathrm{MK}_n^{\mathrm{c}}\left(\mathbb{P}^1, \ldots, \mathbb{P}^n\right)=\mathbb{E}^{\mathbb{P}^*}[\xi]$ should be attained by a martingale measure $\mathbb{P}^* \in$ $\mathcal{M}^c\left(\mathbb{P}^1, \ldots, \mathbb{P}^n\right)$. Similarly, $\mathrm{MK}_{\infty}^{\mathrm{c}}\left(\mathbb{P}^t\right)$ should be attained by a martingale measure in $\mathcal{M}^c\left(\left(\mathbb{P}^t\right)_{t \in(0, T]}\right)$. We note that this corresponds to the core idea of option pricing in mathematical finance: the price of an option from the seller's perspective (the right-hand side of the equations) should coincide with its price from the buyer's perspective (the left-hand side of the equations). In the rest of this article, we mean the above strong dualities when we say the dual formulation.

**Remark**: Although we do not provide proofs for the above duality, we mention that the mathematical justification of the dualities above has been covered by various authors under various assumptions on the canonical space $\Omega$ and on $\xi$. See for example [@beiglboeck2015complete; @bouchard2015arbitrage; @dolinsky2014robust; @dolinsky2014robusttc; @dolinsky2016martingale; @guo2016optimal].

## Link with Skorokhod embedding problem

In this section, we assume that the payoff $\xi\left(S_T, M_T, m_T,\langle S\rangle_T\right)$ depends on the spot $S_T$, the running maximum $M_T$, minimum $m_T$ or the quadratic variation $\langle S\rangle_T$ at $T$.

To link the strong dual formula above with the Skorohod embedding problem, we first review the classical [Dubins–Schwarz theorem](https://en.wikipedia.org/wiki/Dubins%E2%80%93Schwarz_theorem) from stochastic analysis, indicating that every continuous martingale is a stochastic time-change of a standard Brownian motion:

**Lemma (Dubins–Schwarz)**\
Let $M$ be a continuous martingale with respect to a filtration $\mathcal{F}_t$ and $\langle M\rangle_{\infty}=\infty$ and define for all $t \geq 0$ the time-changes (i.e. stopping times) $$
T_t=\inf \left\{s:\langle M\rangle_s>t\right\}
$$ Then $B:=\left(B_t\right):=\left(M_{T_t}\right)$ is a $\mathcal{F}_{T_t}$-Brownian motion and $\left(M_t\right)=\left(B_{\langle M\rangle_t}\right)$.

A proof of this lemma can be found in any textbook on stochastic analysis. Moreover, applying this lemma to the payoff $\xi\left(S_T, M_T, m_T,\langle S\rangle_T\right)$, the dual price given one marginal,$\mathrm{MK}_1^c(\mu)$ as given by strong dual formulation above, can be framed as a constrained perpetual American options: \begin{equation}\label{SEPinvolved}
    \operatorname{MK}_1^c(\mu)=\sup _{\tau \in \mathcal{T}: B_\tau \sim \mu} \mathbb{E}^{\mathbb{P}}\left[\xi\left(B_\tau, \max _{0 \leq s \leq \tau} B_s, \min _{0 \leq s \leq \tau} B_s, \tau\right)\right]
\end{equation} This problem corresponds then to the determination of an (optimal) stopping time $\tau^*$ such that $B_{\tau^*} \sim \mu$. This is a Skorokhod embedding problem (in short SEP). More precisely,

**Definition (Skorokhod Embedding Problem)**\
Find a stopping time $\tau$ such that $B_\tau \sim \mu$ and $B^\tau \equiv\left(B_{t \wedge \tau}\right)_{t \geq 0}$ is uniformly integrable.

### Explicit SEP solutions

In this section, we cite several explicit solutions to SEP. For more details, see \cite{henrylabordere2017model} Section 4.6. We set $M_t \equiv \max _{0<s<t} B_t$ and $m_t \equiv \min _{0<s<t} B_t$.

**Azéma–Yor Solution [@henrylabordere2017model]**\
Define $\tau_{AY} = \inf \{ t \geq 0 : B_t \leq \psi_\mu(M_t) \}$ with $\psi_\mu^{-1}(x) = \frac{\mathbb{E}^\mu[S_T 1_{S_T \geq x}]}{\mathbb{E}^\mu[1_{S_T \geq x}]}$. Then $B_{\tau_{AY}} \sim \mu$.

As the strong dual formulation of the option price requires finding an optimal solution of the SEP under some loss function, we also cite the following optimality solution of the Az\`ema-Yor solution.

**Optimality**: For increasing $g$, $\mathbb{E}[g(M_\tau)] \leq \mathbb{E}[g(M_{\tau_{AY}})]$ [@henrylabordere2017model].

**Perkins Solution[@perkins1986cereteli]**\
Define $\tau_{\text{Perkins}} = \inf \{ t > 0 : B_t \notin (\gamma_+(M_t), \gamma_-(m_t)) \}$ with $\gamma_{+}(j)=\operatorname{argmax}_{x<S_0} \frac{C^\mu(j)-P^\mu(x)}{j-x}$ and $\gamma_{-}(i)=\operatorname{argmin}_{x>S_0} \frac{P^\mu(i)-C^\mu(x)}{x-i}$. Here $C^\mu(x) \equiv \mathbb{E}^\mu\left[\left(S_T-x\right)^{+}\right]$ and $P^\mu(x) \equiv \mathbb{E}^\mu\left[\left(x-S_T\right)^{+}\right]$. Then $B_{\tau_{Perkins}} \sim \mu$. The Perkins embedding has the property that it simultaneously minimizes the law of the maximum $M$ and maximizes the law of the minimum $m$ :

**Optimality**: Let $\tau$ be a solution to SEP. Then for all increasing function $g$, $$
\begin{aligned}
\mathbb{E}\left[g\left(M_\tau\right)\right] & \geq \mathbb{E}\left[g\left(M_{\tau_{\text {Perkins }}}\right)\right] \\
\mathbb{E}\left[g\left(m_\tau\right)\right] & \leq \mathbb{E}\left[g\left(m_{\tau_{\text {Perkins }}}\right)\right].
\end{aligned}
$$

**Vallois' Solution [@vallois1983probleme; @vallois1992quelques]**\
Vallois' embedding uses the [local time](https://en.wikipedia.org/wiki/Local_time_(mathematics)) $L_t^a$ of the Brownian motion at a level $a$. The stopping time is given by

$$
\tau_{\mathrm{V}} = \inf\left\{ t \ge 0 : \int_0^t \varphi(B_s)\,dL_s^a \ge \lambda \right\},
$$

with $\varphi$ and $\lambda$ chosen to ensure

$$
B_{\tau_{\mathrm{V}}} \sim \mu.
$$ Details can be found in @henrylabordere2017model.

### Application to lookback options

Applying the optimality results above to special types of payoff $\xi$ (more precisely, lookback options) in the strong dual pricing formula, we obtain the following robust pricing formula.

**Corollary**\
Suppose that the payoff $\xi$ depends non-decreasingly only on the running maximum of the price process, i.e., $\xi = g(\max_{0\leq t\leq T} S_t)$, the, we have \begin{equation}
        \mathrm{MK}_1^c(\mu) = \mathbb{E}[g(\max_{0\leq t\leq \tau_{AY}} B_t)]
    \end{equation} where $B$ is a Brownian motion. Similarly, suppose that the payoff $\xi$ depends non-decreasingly only on the running minimum of the price process, i.e., $\xi = g(\min_{0\leq t\leq T} S_t)$, the, we have \begin{equation}
        \mathrm{MK}_1^c(\mu) = \mathbb{E}[g(\min_{0\leq t\leq \tau_{Perkins}} B_t)]
    \end{equation} where $B$ is a Brownian motion.

**Proof**: Follows from the optimality of Azéma–Yor and Perkins embeddings.

At the end of this section, we emphasis the significance of this result. The above robust pricing formulas for lookback options significantly simplify the numerical procedure. Previously, one had to optimize over an entire family of hedging strategies or martingale measures to determine the robust price. Now, by leveraging the optimality of the Azéma–Yor and Perkins embeddings, the pricing problem is reduced to simulating a standard Brownian motion along with the corresponding stopping time. This transformation—from a complex, high-dimensional optimization problem to a simulation-based approach—greatly enhances the tractability and efficiency of computing robust prices for path-dependent options.

## Conclusion

In this article, we have developed a dynamic formulation of continuous-time martingale optimal transport and its connection with the Skorokhod embedding problem. Starting from a robust hedging problem, we derived a dual minimax formulation of the pricing formula. We then showed how explicit SEP solutions can be used to price lookback options and indicate the significance.

The following topics are not sufficiently discussed in this article (or in existing research) and we refer interested readers to @henrylabordere2017model (or independent research) for some more details: First, our SEP approach allows matching only one marginal; general SEP, however, includes embedding several marginals into a Brownian motion via stopping times; it is worth a finer study of the general SEP in the setting of continuous-time MOT; the author believes that extension to matching a finite number of marginals shall not bring new technical difficulties, however, matching continuous marginals might require new techniques. Second, the application of SEP in pricing is currently only limited to certain lookback options; it seems rather hard to extend the application to more complex options since the optimality results above are in general hard to acquire for general option payoffs. Third, in the SEP approach, the price is obtained by computing an optimal stopping time; it is not discussed what optimal price process (and what hedging strategy) this stopping time corresponds to; fortunately, there are some discussions on this topic in @henrylabordere2017model Section 4.5 and Section 4.7.

## References
