---
title: "Convergence of Measures and Metrizability"
author: Ashwin Trisal
---

This article addresses narrow and wide convergence of probability measures.

## Nets

When speaking about general topological spaces that are not metric spaces, understanding the convergence of sequences does not determine topology or continuity. A generalization of sequences, known as <b>nets</b>, can be used to show continuity.<ref name="Kelley" /> Roughly, a net consists of a directed set $\{x_\gamma\}_{\gamma\in\Gamma}$: a function from a partially ordered set $\Gamma$ such that for each $\gamma_1,\gamma_2\in\Gamma,\exists \gamma_3\in\Gamma$ such that $\gamma_1,\gamma_2\preceq\gamma_3$. We say that this net converges to $x$ if, for every open set $U\ni x$, there exists some large $a_U$ such that for all $a_U\preceq a$, $x_{\gamma_a}\in U$.

## Weak-star Topologies

Given a Banach space $X$ and its Banach dual $X^*$, the dual can be endowed with the weakest topology that makes the evaluation maps at elements of $X$ continuous. This is called the [weak-\* topology on $X^*$ relative to $X$](https://en.wikipedia.org/wiki/Weak_topology#Weak-*_topology)<ref name="KR" />. By [Banach-Alaoglu](https://en.wikipedia.org/wiki/Banach%E2%80%93Alaoglu_theorem)<ref name="KR" />, the unit ball of $X^*$ (which we call $(X^*)_1$) with the weak-star topology is compact.

In the case where $X$ is norm separable, the weak-star topology on the unit ball of $X^*$ can, in fact, be metrized.<ref name="Rudin" /> Fix a sequence $\{x_n\}_{n=1}^\infty$ that is countable and dense in $X$. Define the metric $d$ by $d(\phi,\psi):=\sum_{n=0}^\infty 2^{-n}\frac{|\phi(x_n)-\psi(x_n)|}{1+|\phi(x_n)-\psi(x_n)|}$. This is a sum of pseudometrics, necessarily convergent because each term is less than or equal to $2^{-n}$, and is nondegenerate because if $d(\phi,\psi)=0$, then $\phi(x_n)=\psi(x_n)$ for each $x_n$, which would imply that the continuous functions $\phi,\psi$ agreed on a dense subset of a metric space. The identity map from $((X^*)_1,w*)$ to $((X^*)_1,d)$ is continuous: choose a convergent net in $(X^*)_1$, $(\phi_\gamma)_{\gamma\in\Gamma} \to \phi$. Then for each $\epsilon>0$, perform the following truncation process: choose a large $N$ so that $\sum_{n=N+1}^\infty 2^{-n}=2^{-N}<\frac{\epsilon}{2}$. Because $\phi_\gamma\xrightarrow{w*}\phi$, for each $n\in\{1,\ldots,N\}$, there is some large $\gamma_n$ such that for all $\gamma\succeq\gamma_n$, $|\phi_\gamma(x_n)-\phi(x_n)|<\frac{\epsilon}{2\cdot N\cdot 2^{-n}}$. By the net order axioms, there is some large $\gamma_0\succeq\gamma_i\forall i\in\{1,\ldots,N\}$. So for each $\gamma\succeq \gamma_0$, $d(\phi_\gamma,\phi)<\sum_{n=1}^N \frac{1}{2N}+\sum_{n=N+1}^\infty 2^{-n}<\epsilon$. Now the identity map between the two spaces is a continuous bijection between a compact and a Hausdorff topological space, and is therefore a homeomorphism. So it metrizes the weak-star topology.

## Metrizability for duals of <math>C(X)</math>-spaces

If $X$ is a compact Hausdorff metric space, $C(X)=C_b(X)=C_0(X)$ is separable, due to the following argument: compact metric spaces are always separable<ref name="SE metric" />. Pick a countable dense subset $\{x_n\}_{n\in\mathbb N}\subseteq X$, and consider the smallest $\mathbb Q$-algebra generated by the functions $d(x,x_n)$. This is a countable union of countable sets and therefore countable. As a subalgebra which separates points and contains the constant function, it must be dense by Stone-Weierstrass. So the unit ball of the dual of $C(X)$ is metrizable.

Conversely, let $X$ be a locally compact Hausdorff topological space, and assume that the unit ball of the dual of $C_b(X)$ is metrizable. Then, because $X\rightarrow (C_b(X))^*$ via point evaluation, which is a norm $1$ map, and because the topology on $X$ is exactly the topology of weak-star convergence in $C_b(X)^*$<ref name="gelfand" />, this means that $X$ is metrizable as well. So $X$ is a metrizable space which lives inside a compact metrizable space. This is in fact equivalent to the Stone-Cech compactification of $X$ being metrizable <ref name="SE stone cech" />, which is quite rare.

## Narrow Convergence

For every finite signed Radon measure $\mu$ on a locally compact Hausdorff space $X$, there is some element $f\in C_0(X)$ such that $\int_X f\,d\mu\neq 0$. Moreover, letting $|\mu|$ denote the total variation of the measure, there is a net of functions $f_\gamma\in C_0(X)$ such that $\int_X f_\gamma\,d\mu\rightarrow |\mu|$, and $\int_X f\,d\mu\le \|f\|_\infty |\mu|$. This means that $\mathcal M(X)\hookrightarrow C_0(X)^*$, and can be isometrically identified with a subset of the dual. In particular, because the total variation norm does not increase with respect to continuous bounded functions, $\mathcal M(X)\hookrightarrow C_b(X)^*$. Narrow convergence is weak-star convergence in $\mathcal M(X)$ with respect to $C_b(X)$: a net of measures $\mu_\gamma$ converges to $\mu$ narrowly if, for every $f\in C_b(X)$, $\int_X f\,d\mu_n\to\int_X f\,d\mu$<ref name="villani" />.

Although in general the topology of narrow convergence is not metrizable on the unit ball -- for example, on any compact Hausdorff space which is not metrizable -- it is on the class of probability measures, so long as $X$ is separable. Take, again, a countable dense subset of $X$, $D$, and taking the family of functions $\mathcal C_2=\{h(x)=(q_1+q_2d(x,y))\wedge k\,|\, q_1,q_2,k\in\mathbb Q, q_2,k\in (0,1), y\in D\}$. Let $\mathcal C_1$ be the family of functions generated by taking infima of finitely many elements of $\mathcal C_2$, and let $\mathcal C_0=\{\lambda h\,|\,\lambda\in\mathbb Q,h\in\mathcal C_1$. This is still countable, and approximates integrals of elements of $C_b$ well weakly-star, so there is a metric on the probabilities by enumerating $\mathcal C_0=\{f_k\}_{k=1}^\infty$, and $d(\mu,\nu)=\sum_{k=1}^\infty 2^{-k}|\int f_k\,d\mu-\int f_k\,d\nu|$<ref name="Ambrosio" />.

## Wide Convergence

Wide convergence is the weak-star convergence with respect to elements of $C_0(X)$ rather than $C_b(X)$<ref name="villani" />. As such, it is a weaker topology on the class of probability measures. When $X$ is a locally compact separable metric space (in particular, locally compact metric spaces which are $\sigma$-compact are separable), we can find a separating family of functions which form a countable subalgebra. One way to do this is by taking, for each point $x_n$ in a countable dense subset, a compact neighborhood $K_n\ni x_n$ and taking a partition of unity subordinate to that compact, $\varphi_n$. Taking the $\mathbb Q$-algebra generated by this countable family of functions will separate points, which will make it dense in $C_0(X)$ by Stone-Weierstrass. So $C_0(X)$ is separable, which means that the unit ball of the dual is metrizable.

## References

<references> <ref name="KR">Kadison, Ringrose. *Fundamentals of the Theory of Operator Algebras, Volume I.* Ch. 1.3, 1.6. Academic Press, 1983.</ref> <ref name="Kelley">Kelley, *General Topology* Ch. 2. Springer, 1975.</ref> <ref name="Rudin">Rudin, *Functional Analysis* Ch. 3. 1991.</ref> <ref name="SE metric">[Math StackExchange, *Prove if* $X$ is a compact metric space, then $X$ is separable. 2020.](https://math.stackexchange.com/questions/974233/prove-if-x-is-a-compact-metric-space-then-x-is-separable/974252)</ref> <ref name="SE stone cech">[Math StackExchange, *Stone-Cech via* $C_b(X)\cong C(\beta X)$. 2020.](https://math.stackexchange.com/questions/260794/stone-%c4%8cech-via-c-bx-cong-c-beta-x)</ref> <ref name="Ambrosio">[Ambrosio, Gigli, Savaré. *Gradient Flows.* Ch. 5.1. 2000](http://www2.stat.duke.edu/~sayan/ambrosio.pdf)</ref> <ref name="gelfand">\[http://www.mathnet.ru/php/archive.phtml?wshow=paper&jrnid=sm&paperid=6155&option_lang=eng Gelfand, Naimark. *On the imbedding of normed rings into the ring of operators on Hilbert space.* 1943.</ref> <ref name="villani">[Villani. *Optimal transport, old and new.* 2006.](https://ljk.imag.fr/membres/Emmanuel.Maitre/lib/exe/fetch.php?media=b07.stflour.pdf)</ref> </references>
