---
title: "New Article Ideas"
bibliography: bibliography.bibtex
---

Below, you can find a list of new article ideas and suggested references.

Feel free to incorporate additional references! Please list all references you use at the bottom of your article.

If you choose to write about one of these ideas, let me know, and I will remove it from the list below. Want to write about something that's not listed here? Great! Let me know, and I will suggest some references.

# Variants of Optimal Transport Problems

-   The $s$-Wasserstein metric for $s<1$ [Craig and Yu, 2024](https://arxiv.org/abs/2411.12153), Santambrogio 3.3.2

-   Entropic optimal transport, Chewi, Niles-Weed, Rigollet Ch.4 and [2](https://www.math.columbia.edu/~mnutz/docs/EOT_lecture_notes.pdf)

-   Connections between entropic optimal transport and the Schrödinger bridge problem [1](https://www.math.ucdavis.edu/~saito/data/acha.read.s19/leonard_survey-schroedinger-problem-optxport.pdf)

-   Brenier maps [3](https://arxiv.org/abs/2404.02855)

-   Knothe maps, Figalli-Glaudo (9-14), [Carlier, et. al. '08](https://arxiv.org/abs/0810.4153)

# The 2-Wasserstein Metric

-   Multi-marginal optimal transport and density functional theory

-   Displacement convexity; Santambrogio (249-251,271-276); Villani (150-154) (make sure to cite existing wiki article on Geodesics and generalized geodesics)

# Numerical Methods for Optimal Transport

-   Computing OT via Benamou-Brenier; Santambrogio (220-225); Peyré, Cuturi (102-108)

-   Wasserstein Barycenters; Santambrogio (215-218); Peyré, Cuturi (138-144)

# Wasserstein Gradient Flows

-   Fundamentals of Wasserstein Gradient flows, Chewi, Niles-Weed, Rigollet (135-148) and Santambrogio, 'Euclidean, Metric, and Wasserstein GFs'

# Mathematical Foundations

-   Gradient flows in metric spaces; Figalli-Glaudo (107-108); Santambrogio, 'OT for Applied Mathematicians' (285-290); Santambrogio, 'Euclidean, Metric, and Wasserstein GFs' (90-107; don't need to cover all topics, just what interests you)

# Statistical Foundations

-   Estimation of Wasserstein distances, Chewi, Niles-Weed, Rigollet Ch.2
-   Estimation of transport maps, Chewi, Niles-Weed, Rigollet Ch.3

# Applications:

-   Optimal transport methods in economics; see introduction of book by Galichon (I have a copy you can borrow) and [6](https://arxiv.org/abs/2107.04700)

-   Quantization and Lloyd's algorithm [7](https://hal.science/hal-03256039/document), [8](https://link.springer.com/content/pdf/10.1007/978-3-030-01947-1_7.pdf), [9](https://link.springer.com/content/pdf/10.1007/978-3-319-99689-9_6.pdf)

-   Transformers as Wasserstein Gradient Flows; Chewi, Niles-Weed, Rigollet (195-200)

-   Inferring developmental trajectories of biological cells via optimal transport [Waddington-OT](https://broadinstitute.github.io/wot/tutorial/), [Schiebinger, et. al. 2019](https://www.cell.com/cell/fulltext/S0092-8674(19)30039-X)
